### ISSUE TITLE
Appendix 03: The Content Pipeline

### ISSUE THREAD

**Issue by AristurtleDev** [AristurtleDev/building-2d-games-with-monogame#15]
# Appendix 03: The Content Pipeline Feedback

Please use this issue to discuss feedback specific to [Appendix 03: The Content Pipeline](https://github.com/AristurtleDev/building-2d-games-with-monogame/blob/main/documentation/appendix-03-the-content-pipeline.md)

## Feedback Guidelines
When providing feedback, please adhere to the following guidelines 

- Provide feedback relevant to the chapter as defined by the title of this issue.
- For typos and grammatical errors, please provide them as a list with the line number they occur on.  Do not separate them into individual feedback sections based on paragraphs
- Use `#` headers where appropriate.  Do not use them just to enlarge text
- When correcting grammar, please ensure it is an actual grammar correction and not a personal opinion on how something should be written.  
- Inline with the above, suggestions on wording something better is encouraged, but please bear in mind that this tutorial is meant for developers who are already have a base understanding of C# as defined in the Preface documentation, and the tutorial is focused on teaching game development with MonoGame and not teaching C# programming.

## Feedback Template
To make providing feedback easier, You can copy and paste the following template into your comment submission

```md
## Chapter Feedback
<!-- provide feedback here related to the overall chapter.  Suggestions such as missing information, better explanations of topics, or removal of irrelevant content. -->

## Typos
<!-- provide a list here containing the line number and the typo made with a suggested correction -->
```

**Comment by titanix** [comment]
First code block: the line `if (GamePad.GetState(PlayerIndex.One).Buttons.Back == ButtonState.Pressed || Keyboard.GetState().IsKeyDown(Keys.Escape))` is long enough that it doesn't display totally on a 1800px wide resolution. I recommend using a new line so that there is not horizontal scroll bar.
In addition, I suggest using parenthesis after the condition, to teach the best practices to beginner.

```
if (GamePad.GetState(PlayerIndex.One).Buttons.Back == ButtonState.Pressed 
    || Keyboard.GetState().IsKeyDown(Keys.Escape))
{
    Exit();
}
```

Line 73: `The first thing you'll notice [...] two instance member fields; a GraphicsDeviceManager` ';' is probably a typo and should be changed to ','.

Personal opinion : `When the base method is called, this is when the graphics device object is instantiated.` => `The graphics device object is instantiated when the base method is called.`

Line 132: missing interrogation point at the end of line.
